filmomania1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls')),
    path('filmovi/', include('filmovi.urls')),
    path('serije/', include('serije.urls')),
    path('domaci-filmovi/', include('domaci_filmovi.urls')),
    path('domace-serije/', include('domace_serije.urls')),
    path('tag/', include('tagged.urls')),

    path('video/', include('video.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# prva baza podataka
# PGHOST='ep-winter-grass-a2tqpm2x.eu-central-1.aws.neon.tech'
# PGDATABASE='neondb'
# PGUSER='AndrejWiseman'
# PGPASSWORD='VplMtR5hUF9q'

filmovi/urls.py
from django.urls import path

from .views import filmovi, filmovi_detail_view, tagged

app_name = 'filmovi'

urlpatterns = [
    path('', filmovi, name='filmovi'),

    path('<slug:slug>/', filmovi_detail_view, name='filmovi_detail'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),

]

home/urls.py
from django.urls import path
from .views import home, tagged

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),
]

filmovi/models.py
from django.db import models
from django.urls import reverse

from taggit.managers import TaggableManager


# Create your models here.
class Filmovi(models.Model):
    title = models.CharField(max_length=120)
    originalni_naziv = models.CharField(max_length=120, null=False)
    slug = models.SlugField(default="", null=False)
    godina = models.CharField(max_length=120, null=False, blank=False)
    tags = TaggableManager()
    imdb_ocena = models.CharField(max_length=120, null=False)
    description = models.TextField()
    link_za_preuzimanje = models.CharField(default="", max_length=320)
    link_za_prevod = models.CharField(default="", max_length=320)
    link_za_gledanje = models.CharField(default="", max_length=320)
    image = models.FileField(upload_to='movie-images', null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True, null=False, blank=False)

    def get_absolute_url(self):
        return reverse('filmovi:filmovi_detail', kwargs={'slug': self.slug})

filmovi/views.py
from django.shortcuts import render, get_object_or_404
from .models import Filmovi
from taggit.models import Tag
from django.db.models import Count


# Create your views here.
def filmovi(request):

    queryset = Filmovi.objects.all().order_by('-date')

    common_tags = Filmovi.tags.most_common().annotate(num_times=Count('taggit_taggeditem_items')).order_by(
        '-num_times')

    context = {
        'queryset': queryset,
        'common_tags': common_tags
    }
    return render(request, 'filmovi/film-list.html', context)


def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = Filmovi.tags.most_common()
    queryset = Filmovi.objects.filter(tags=tag)

    context = {
        'tag': tag,
        'queryset': queryset,
        'common_tags': common_tags
    }
    return render(request, 'filmovi/film-list.html', context)


def filmovi_detail_view(request, slug):
    object = get_object_or_404(Filmovi, slug=slug)
    context = {
        'object': object
    }
    return render(request, 'filmovi/detail.html', context)

templates/filmovi/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block content %}


    <div class="detail-kontejner">

        <div class="detail-top">
            <div class="detail-slika">
                <img src="{{ object.image.url }}" alt="slika">
            </div>
            <div class="detail-info">
                <h1 class="detail-naslov">{{ object.title }}</h1>
                <h5>Originalni naziv: {{ object.originalni_naziv }}</h5>
                
                <div class="detail-god">
                    <p class="godina">{{ object.godina }}</p>
                    <p class="zanr">{{ object.tags.all|join:" / " }}</p>
                    
                </div>
                <div class="detail-preuzmi">
                    <p class="imdb"><span class="im">IMDb</span> {{ object.imdb_ocena }}</p>
{#                    <div class="detail-preu">#}
{#                        <a href="#" class="btn btn-info mt-1">Preuzmi film</a>#}
{#                        <a href="#" class="btn btn-warning mt-1">Preuzmi prevod</a>#}
{#                    </div>#}
{#                    <a href="#" class="btn btn-info mt-1">Gledaj online</a>#}


                    <div class="d-grid gap-2">
                      <div class="detail-preu">
                        <a href="{{ object.link_za_preuzimanje }}" class="btn btn-info mt-1">Preuzmi film</a>
                        <a href="{{ object.link_za_prevod }}" class="btn btn-info mt-1">Preuzmi prevod</a>
                      </div>
                      <a href="{{ object.link_za_gledanje }}" target="_blank" class="btn btn-primary mt-1">Gledaj online</a>
                    </div>
                </div>
            </div>

        </div>
            

        <div class="detail-sadrzaj">
            <h3>Sadrzaj:</h3>
            <div class="detail-tekst">
                <p>
                    {{ object.description | safe }}
                </p>
            </div>
        </div>

    </div>

    
{% endblock %}

templates/filmovi/film-list.html
{% extends 'base.html' %}

{% block title %}
    Filmovi | {{ tag.name | capfirst }}
{% endblock %}


{% block content %}

    {% if tag.name %}
        <h1 class="podeok2">
            {{ tag.name | capfirst }}
        </h1>
    {% else %}
        <h1 class="podeok">
            Filmovi
        </h1>
    {% endif %}

    <div class="kontejner">

        <div class="tags">
            <h5>Zanrovi</h5>
            <p>Broj filmova: {{ queryset.count }}</p>

            <div class="zanr">
                <a href="{% url 'filmovi:filmovi' %}">Svi filmovi</a>
                {% for mt in common_tags %}
                    <a href="{% url 'filmovi:tagged' mt.slug %}">{{ mt | capfirst}} ({{ mt.num_times }})</a>
                {% endfor %}
            </div>
        </div>

        <div class="lista">
        {% if queryset %}
          {% for qs in queryset %}
              <div class="objekt">
                  <a href="{{ qs.get_absolute_url }}" class="">
                      <img src="{{ qs.image.url }}" alt="{{ qs.title }}" class="slicica">
                  </a>
                  <p class="title">{{ qs.title }}</p>
                  <p class="god-imdb"><small>{{ qs.godina }} | <span class="">IMDb</span> {{ qs.imdb_ocena }}</small></p>
              </div>
          {% endfor %}
        {% else %}
            <p>Nema filmova.</p>
        {% endif %}
        </div>
    </div>
    
{% endblock %}