domace_serije/urls.py
from django.urls import path
from .views import domace_serije, domace_s_detail, tagged

app_name = 'domace_serije'

urlpatterns = [
    path('', domace_serije, name='domace_serije'),
    path('<slug:slug>/', domace_s_detail, name='domace_s_detail'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),
]

filmomania1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls')),
    path('filmovi/', include('filmovi.urls')),
    path('serije/', include('serije.urls')),
    path('domaci-filmovi/', include('domaci_filmovi.urls')),
    path('domace-serije/', include('domace_serije.urls')),
    path('tag/', include('tagged.urls')),

    path('video/', include('video.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# prva baza podataka
# PGHOST='ep-winter-grass-a2tqpm2x.eu-central-1.aws.neon.tech'
# PGDATABASE='neondb'
# PGUSER='AndrejWiseman'
# PGPASSWORD='VplMtR5hUF9q'

home/urls.py
from django.urls import path
from .views import home, tagged

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),
]

domace_serije/models.py
from django.db import models
from django.urls import reverse

from taggit.managers import TaggableManager


# Create your models here.
class DomaceSerije(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(default="", null=False)
    godina = models.CharField(max_length=120, null=False, blank=False)
    description = models.TextField()
    tags = TaggableManager()
    image = models.FileField(upload_to='movie-images', null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True, null=False, blank=False)

    def get_absolute_url(self):
        return reverse('domace_serije:domace_s_detail', kwargs={'slug': self.slug})


class Epizoda(models.Model):
    epizode = models.ForeignKey(DomaceSerije, on_delete=models.CASCADE)
    epizode_date = models.DateField(auto_now_add=True)
    sezona = models.CharField(max_length=120, null=True, blank=True)
    ep = models.CharField(max_length=120, null=True, blank=True)
    epizode_link = models.CharField(max_length=300)
    epizode_preuzmi = models.CharField(default='', max_length=300)

    def __str__(self):
        return self.ep

domace_serije/views.py
from django.shortcuts import render, get_object_or_404
from .models import DomaceSerije, Epizoda
from taggit.models import Tag
from django.db.models import Count


# Create your views here.
def domace_serije(request):

    queryset = DomaceSerije.objects.all().order_by('-date')

    common_tags = DomaceSerije.tags.most_common().annotate(num_times=Count('taggit_taggeditem_items')).order_by(
        '-num_times')

    context = {
        'queryset': queryset,
        'common_tags': common_tags
    }
    return render(request, 'domace-serije/domace-s-list.html', context)


def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = DomaceSerije.tags.most_common()
    queryset = DomaceSerije.objects.filter(tags=tag)

    context = {
        'tag': tag,
        'queryset': queryset,
        'common_tags': common_tags
    }
    return render(request, 'domace-serije/domace-s-list.html', context)


def domace_s_detail(request, slug):
    obj = get_object_or_404(DomaceSerije, slug=slug)
    epiz = Epizoda.objects.filter(epizode=obj).order_by('-epizode_date')

    context = {
        'object': obj,
        'epiz': epiz
    }
    return render(request, 'domace-serije/domace-s-detail.html', context)

templates/domace-serije/domace-s-detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block content %}


    <div class="detail-kontejner">

        <div class="detail-top">
            <div class="detail-slika">
                <img src="{{ object.image.url }}" alt="slika">
            </div>
            <div class="detail-info">
                <h1 class="detail-naslov">{{ object.title }}</h1>
                
{#                <div class="detail-god">#}
{#                    <p class="godina">{{ object.godina }}</p>#}
{#                    <p class="zanr">{{ object.zanr }}</p>#}
{#                </div>#}
                <div class="detail-god">
                    <p class="godina">{{ object.godina }}</p>
                    <p class="zanr">{{ object.tags.all|join:" / " }}</p>
                </div>
                <div class="detail-preuzmi">
                    
                </div>
            </div>

        </div>

        <div class="detail-sadrzaj">
            <h3>Sadrzaj:</h3>
            <div class="detail-tekst">
                <p>
                    {{ object.description | safe }}
                </p>
            </div>
        </div>

        <div class="linkovi">
            
            <ul class="list-group list-group-flush">
                {% for e in epiz %}
                    <li class="list-group-item list-group-item-dark">
                        Sezona: {{ e.sezona }} Epizoda: {{ e.ep }}
                        <a href="{{ e.epizode_link }}" class="btn btn-primary btn-sm" target="_blank">Gledaj</a>
                        <a href="{{ e.epizode_preuzmi }}" class="btn btn-info btn-sm m-1">Preuzmi</a>
                    </li>
                {% endfor %}
            </ul>
        </div>

    </div>
    
    
{% endblock %}

templates/domace-serije/domace-s-list.html
{% extends 'base.html' %}

{% block title %}
    Domace serije
{% endblock %}


{% block content %}
    <h1 class="podeok">Domace serije</h1>

    <div class="kontejner">
    
        <div class="tags">
            <h5>Zanrovi</h5>
            <p>Broj serija: {{ queryset.count }}</p>

            <div class="zanr">
                <a href="{% url 'domace_serije:domace_serije' %}">Sve domace serije</a>
                {% for mt in common_tags %}
                    <a href="{% url 'domace_serije:tagged' mt.slug %}">{{ mt | capfirst}} ({{ mt.num_times }})</a>
                {% endfor %}
            </div>
        </div>
    
        <div class="lista">
          {% for qs in queryset %}
              <div class="objekt">
                  <a href="{{ qs.get_absolute_url }}" class="">
                      <img src="{{ qs.image.url }}" alt="{{ qs.title }}" class="slicica">
                  </a>
                  <p>{{ qs.title }}</p>
              </div>
            {% endfor %}
        </div>
    </div>
    
{% endblock %}