domace_serije/urls.py
from django.urls import path
from .views import domace_serije, domace_s_detail, tagged

app_name = 'domace_serije'

urlpatterns = [
    path('', domace_serije, name='domace_serije'),
    path('<slug:slug>/', domace_s_detail, name='domace_s_detail'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),
]

domaci_filmovi/urls.py
from django.urls import path
from .views import domaci_filmovi, domaci_f_detail, tagged, video

app_name = 'domaci_filmovi'

urlpatterns = [
    path('', domaci_filmovi, name='domaci_filmovi'),
    path('<slug:slug>/', domaci_f_detail, name='domaci_f_detail'),
    path('video/<slug:slug>/', video, name='video'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),
]

filmomania1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls')),
    path('filmovi/', include('filmovi.urls')),
    path('serije/', include('serije.urls')),
    path('domaci-filmovi/', include('domaci_filmovi.urls')),
    path('domace-serije/', include('domace_serije.urls')),
    path('tag/', include('tagged.urls')),

    path('video/', include('video.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# prva baza podataka
# PGHOST='ep-winter-grass-a2tqpm2x.eu-central-1.aws.neon.tech'
# PGDATABASE='neondb'
# PGUSER='AndrejWiseman'
# PGPASSWORD='VplMtR5hUF9q'

filmovi/urls.py
from django.urls import path

from .views import filmovi, filmovi_detail_view, tagged

app_name = 'filmovi'

urlpatterns = [
    path('', filmovi, name='filmovi'),

    path('<slug:slug>/', filmovi_detail_view, name='filmovi_detail'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),

]

home/urls.py
from django.urls import path
from .views import home, tagged

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),
]

serije/urls.py
from django.urls import path
from .views import serije, serije_detail, tagged

app_name = 'serije'
urlpatterns = [
    path('', serije, name='serije'),

    path('<slug:slug>/', serije_detail, name='serije-detail'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),

]

tagged/urls.py
from django.urls import path
from .views import tagged

app_name = 'tagged'

urlpatterns = [
    # path('', tagged, name='tagged'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),
]

video/urls.py
from django.urls import path
from.views import video

urlpatterns = [
    path('', video, name='video'),
]

tagged/models.py
from django.db import models

# Create your models here.

video/models.py
from django.db import models

# Create your models here.

tagged/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from itertools import chain
import itertools
from operator import attrgetter

from django.shortcuts import render

from filmovi.models import Filmovi
from serije.models import Serije
from domaci_filmovi.models import DomaciFilmovi
from domace_serije.models import DomaceSerije

from taggit.models import Tag

# Create your views here.
def tagged(request, slug):
    # Dohvaćanje taga koji odgovara slug-u
    tag = get_object_or_404(Tag, slug=slug)

    # Filtriranje filmova i serija po tagu
    common_tags_film = Filmovi.tags.most_common().annotate(num_times=Count('taggit_taggeditem_items')).order_by(
        '-num_times')
    common_tags_serija = Serije.tags.most_common().annotate(num_times=Count('taggit_taggeditem_items')).order_by(
        '-num_times')
    common_tags_domaci_f = DomaciFilmovi.tags.most_common().annotate(num_times=Count('taggit_taggeditem_items')).order_by(
        '-num_times')
    common_tags_domace_s = DomaciFilmovi.tags.most_common().annotate(
        num_times=Count('taggit_taggeditem_items')).order_by(
        '-num_times')
    # Spajanje tagova iz oba modela i uklanjanje duplikata
    common_tags = list(set(list(common_tags_film) + list(common_tags_serija) + list(common_tags_domaci_f) + list(common_tags_domace_s)))

    queryset_f = Filmovi.objects.filter(tags=tag)
    queryset_s = Serije.objects.filter(tags=tag)
    queryset_df = DomaciFilmovi.objects.filter(tags=tag)
    queryset_ds = DomaceSerije.objects.filter(tags=tag)


    # Kombiniranje filmova i serija u jedan queryset
    kombinirani_qs = list(set(list(queryset_s) + list(queryset_f) + list(queryset_df) + list(queryset_ds)))


    # Sortiranje kombiniranog queryseta po datumu
    # sortirano_po_datumu = sorted(kombinirani_qs, key=attrgetter('date'), reverse=True)

    context = {
        'tag': tag,
        'common_tags': common_tags,
        'kombinirani_qs': kombinirani_qs,

    }
    return render(request, 'tagged.html', context)

video/views.py
from django.shortcuts import render


# Create your views here.
def video(request):

    context = {

    }
    return render(request, 'video.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Pocetna{% endblock %} | FilmoManiA</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'myglobalcss.css' %}">
    <link rel="stylesheet" href="{% static 'mojstatic.css' %}">
    {% block css %}{% endblock %}
</head>
<body>

{% include 'navbar.html' %}

{% block content %}
{% endblock %}

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">&copy;  {% now "M Y" %} FilmoMania</p>


    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="{% url 'home:home' %}" class="nav-link px-2 text-secondary">Pocetna</a></li>
      <li class="nav-item"><a href="{% url 'filmovi:filmovi' %}" class="nav-link px-2 text-secondary">Filmovi</a></li>
    </ul>
  </footer>
</div>

templates/navbar.html
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand logo" href="{% url 'home:home' %}">Filmo<span>M</span>ani<span>A</span></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'home:home' %}">Pocetna</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'filmovi:filmovi' %}">Filmovi</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'serije:serije' %}">Serije</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'domaci_filmovi:domaci_filmovi' %}">Domaci filmovi</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'domace_serije:domace_serije' %}">Domace serije</a>
        </li>
      </ul>
      <div class="d-flex" >
{#        <a class="btn btn-outline-warning" type="button">Login</a>#}
      </div>
    </div>
  </div>
</nav>

templates/tagged.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{#    <link rel="stylesheet" href="{% static 'homestatic.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'tagged.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'home.css' %}">#}
{% endblock %}

{% block title %}
    {{ tag.name | capfirst }}
{% endblock %}


{% block content %}

{#    {% if tag.name %}#}
        <h1 class="podeok2">
            {{ tag.name | capfirst }}
        </h1>
{#    {% else %}#}
{#        <h1 class="podeok">#}
{#            Filmovi#}
{#        </h1>#}
{#    {% endif %}#}

    <div class="kontejner">

        <div class="tags">
            <h5>Zanrovi</h5>
{#            <p><small>Ukupno filmova i serija: {{  }}</small></p>#}
        

            <div class="zanr">
                <a href="{% url 'filmovi:filmovi' %}">Svi filmovi</a>
                <a href="{% url 'serije:serije' %}">Sve serije</a>
                <a href="{% url 'domaci_filmovi:domaci_filmovi' %}">Svi domaci filmovi</a>
                <a href="{% url 'domace_serije:domace_serije' %}">Sve domace serije</a>
                {% for mt in common_tags %}
                    <a href="{% url 'tagged:tagged' mt.slug %}">{{ mt | capfirst}}</a>
                {% endfor %}
            </div>
        </div>

        <div class="lista">
{#        {% if queryset %}#}
          {% for c in kombinirani_qs %}
              <div class="objekt">
                  <a href="{{ c.get_absolute_url }}" class="">
                      <img src="{{ c.image.url }}" alt="{{ c.title }}" class="slicica">
                  </a>
                  <p>{{ c.title }}</p>
              </div>
          {% endfor %}
{#        {% else %}#}
{#            <p>Nema filmova.</p>#}
{#        {% endif %}#}
        </div>
    </div>

{% endblock %}

templates/video.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'video-static.css' %}">
{% endblock %}

{% block content %}

    <h1>{{ obj.title }}</h1>

    <div class="video-kontejner">
        <div class="video">
                <iframe
                        src="{{ obj.link_za_gledanje }}"
                         width="1280" height="720"  title="{{ obj.title }}">
                </iframe>

        </div>
    </div>

{% endblock %}

{#https://yyrxh-my.sharepoint.com/:v:/g/personal/andrej_yyrxh_onmicrosoft_com/Ecwi3U8-F_tNt5zl1McA2HQBA562JO7cfAfaI8V42GaXeA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=GRGEwh#}

{#https://yyrxh-my.sharepoint.com/:v:/g/personal/andrej_yyrxh_onmicrosoft_com/EU4j_dc5IeNPpDqet1-8_pkB3PuuX4EYkruyDnFfaM_4IQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=1tiwHC#}