domaci_filmovi/urls.py
from django.urls import path
from .views import domaci_filmovi, domaci_f_detail, tagged, video

app_name = 'domaci_filmovi'

urlpatterns = [
    path('', domaci_filmovi, name='domaci_filmovi'),
    path('<slug:slug>/', domaci_f_detail, name='domaci_f_detail'),
    path('video/<slug:slug>/', video, name='video'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),
]

filmomania1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls')),
    path('filmovi/', include('filmovi.urls')),
    path('serije/', include('serije.urls')),
    path('domaci-filmovi/', include('domaci_filmovi.urls')),
    path('domace-serije/', include('domace_serije.urls')),
    path('tag/', include('tagged.urls')),

    path('video/', include('video.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# prva baza podataka
# PGHOST='ep-winter-grass-a2tqpm2x.eu-central-1.aws.neon.tech'
# PGDATABASE='neondb'
# PGUSER='AndrejWiseman'
# PGPASSWORD='VplMtR5hUF9q'

home/urls.py
from django.urls import path
from .views import home, tagged

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('zanr/<slug:slug>/', tagged, name='tagged'),
]

domaci_filmovi/models.py
from django.db import models
from django.urls import reverse

from taggit.managers import TaggableManager


# Create your models here.
class DomaciFilmovi(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(default="", null=False)
    godina = models.CharField(max_length=120, null=False, blank=False)
    tags = TaggableManager()
    description = models.TextField()
    link_za_preuzimanje = models.CharField(default="", max_length=320)
    link_za_gledanje = models.CharField(default="", max_length=320)
    image = models.FileField(upload_to='movie-images', null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True, null=False, blank=False)

    def get_absolute_url(self):
        return reverse('domaci_filmovi:domaci_f_detail', kwargs={'slug': self.slug})

domaci_filmovi/views.py
from django.shortcuts import render, get_object_or_404
from .models import DomaciFilmovi
from taggit.models import Tag
from django.db.models import Count


# Create your views here.
def domaci_filmovi(request):

    queryset = DomaciFilmovi.objects.all().order_by('-date')

    common_tags = DomaciFilmovi.tags.most_common().annotate(num_times=Count('taggit_taggeditem_items')).order_by(
        '-num_times')

    context = {
        'queryset': queryset,
        'common_tags': common_tags
    }
    return render(request, 'domaci-filmovi/domaci-f-list.html', context)


def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = DomaciFilmovi.tags.most_common()
    queryset = DomaciFilmovi.objects.filter(tags=tag)

    context = {
        'tag': tag,
        'queryset': queryset,
        'common_tags': common_tags
    }
    return render(request, 'domaci-filmovi/domaci-f-list.html', context)


def domaci_f_detail(request, slug):
    object = get_object_or_404(DomaciFilmovi, slug=slug)
    context = {
        'object': object
    }
    return render(request, 'domaci-filmovi/domaci-f-detail.html', context)


def video(request, slug):
    obj = get_object_or_404(DomaciFilmovi, slug=slug)

    context = {
        'obj': obj
    }

    return render(request, 'video.html', context)

templates/domaci-filmovi/domaci-f-detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block content %}


    <div class="detail-kontejner">

        <div class="detail-top">
            <div class="detail-slika">
                <img src="{{ object.image.url }}" alt="slika">
            </div>
            <div class="detail-info">
                <h1 class="detail-naslov">{{ object.title }}</h1>
                
                <div class="detail-god">
                    <p class="godina">{{ object.godina }}</p>
                    <p class="zanr">{{ object.tags.all|join:" / " }}</p>
                    
                </div>
                <div class="detail-preuzmi">
                    <a href="{{ object.link_za_preuzimanje }}" class="btn btn-warning mt-1">Preuzmi</a>
{#                    <a href="{% url 'domaci_filmovi:video' object.slug %}" class="btn btn-info mt-1">Gledaj online</a>#}
                    <a href="{{ object.link_za_gledanje }}" class="btn btn-info mt-1" target="_blank">Gledaj online</a>
                </div>
            </div>

        </div>
            

        <div class="detail-sadrzaj">
            <h3>Sadrzaj:</h3>
            <div class="detail-tekst">
                <p>
                    {{ object.description | safe }}
                </p>
            </div>
        </div>

    </div>

    
{% endblock %}

{#https://yyrxh-my.sharepoint.com/:v:/g/personal/andrej_yyrxh_onmicrosoft_com/EU4j_dc5IeNPpDqet1-8_pkB3PuuX4EYkruyDnFfaM_4IQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=3HSSFl#}

templates/domaci-filmovi/domaci-f-list.html
{% extends 'base.html' %}

{% block title %}
    Domaci Filmovi | {{ tag.name | capfirst }}
{% endblock %}


{% block content %}

    {% if tag.name %}
        <h1 class="podeok2">
            {{ tag.name | capfirst }}
        </h1>
    {% else %}
        <h1 class="podeok">
            Domaci filmovi
        </h1>
    {% endif %}

    <div class="kontejner">

        <div class="tags">
            <h5>Zanrovi</h5>
            <p>Broj filmova: {{ queryset.count }}</p>

            <div class="zanr">
                <a href="{% url 'domaci_filmovi:domaci_filmovi' %}">Svi filmovi</a>
                {% for mt in common_tags %}
                    <a href="{% url 'domaci_filmovi:tagged' mt.slug %}">{{ mt | capfirst}} ({{ mt.num_times }})</a>
                {% endfor %}
            </div>
        </div>

        <div class="lista">
        {% if queryset %}
          {% for qs in queryset %}
              <div class="objekt">
                  <a href="{{ qs.get_absolute_url }}" class="">
                      <img src="{{ qs.image.url }}" alt="{{ qs.title }}" class="slicica">
                  </a>
                  <p class="title">{{ qs.title }}</p>
                  <p class="god-imdb"><small>{{ qs.godina }}</small></p>
              </div>
          {% endfor %}
        {% else %}
            <p>Nema filmova.</p>
        {% endif %}
        </div>
    </div>
    
{% endblock %}